version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: hakathon-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - "3308:3306" 
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hakathon-app
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db       
      DB_PORT: 3306
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: >
      sh -c "npx knex migrate:latest &&
             npx knex seed:run &&
             node dist/index.js"

volumes:
  db_data:
